In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("hotel_bookings.csv")

In [5]:
df.head

<bound method NDFrame.head of               hotel  is_canceled  lead_time  arrival_date_year  \
0      Resort Hotel            0        342               2015
1      Resort Hotel            0        737               2015
2      Resort Hotel            0          7               2015
3      Resort Hotel            0         13               2015
4      Resort Hotel            0         14               2015
...             ...          ...        ...                ...
29259  Resort Hotel            0        386               2016
29260  Resort Hotel            0         77               2016
29261  Resort Hotel            0        134               2016
29262  Resort Hotel            0        220               2016
29263  Resort Hotel            0        189               2016

      arrival_date_month  arrival_date_week_number  arrival_date_day_of_month  \
0                   July                        27                          1
1                   July                        27                          1
2                   July                        27                          1
3                   July                        27                          1
4                   July                        27                          1
...                  ...                       ...                        ...
29259            October                        43                         20
29260            October                        43                         17
29261            October                        43                         17
29262            October                        43                         17
29263            October                        43                         21

       stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
0                            0                     0       2  ...
1                            0                     0       2  ...
2                            0                     1       1  ...
3                            0                     1       1  ...
4                            0                     2       2  ...
...                        ...                   ...     ...  ...
29259                        1                     3       2  ...
29260                        2                     5       2  ...
29261                        2                     5       2  ...
29262                        2                     5       2  ...
29263                        1                     2       3  ...

       deposit_type  agent company days_in_waiting_list    customer_type  \
0        No Deposit    NaN     NaN                    0        Transient
1        No Deposit    NaN     NaN                    0        Transient
2        No Deposit    NaN     NaN                    0        Transient
3        No Deposit  304.0     NaN                    0        Transient
4        No Deposit  240.0     NaN                    0        Transient
...             ...    ...     ...                  ...              ...
29259    No Deposit    NaN     NaN                    0  Transient-Party
29260    No Deposit    NaN     NaN                    0        Transient
29261    No Deposit  240.0     NaN                    0        Transient
29262    No Deposit  243.0     NaN                    0         Contract
29263    No Deposit  314.0     NaN                    0        Transient

          adr  required_car_parking_spaces  total_of_special_requests  \
0        0.00                            0                          0
1        0.00                            0                          0
2       75.00                            0                          0
3       75.00                            0                          0
4       98.00                            0                          1
...       ...                          ...                        ...
29259   49.00                            0                          0
29260   10.00                            0                          0
29261  100.00                            0                          2
29262   72.75                            0                          0
29263   72.56                            0                          1

       reservation_status reservation_status_date
0               Check-Out              2015-07-01
1               Check-Out              2015-07-01
2               Check-Out              2015-07-02
3               Check-Out              2015-07-02
4               Check-Out              2015-07-03
...                   ...                     ...
29259           Check-Out              2016-10-24
29260           Check-Out              2016-10-24
29261           Check-Out              2016-10-24
29262           Check-Out              2016-10-24
29263           Check-Out                 2016-10

[29264 rows x 32 columns]>

In [6]:
df.tail

<bound method NDFrame.tail of               hotel  is_canceled  lead_time  arrival_date_year  \
0      Resort Hotel            0        342               2015
1      Resort Hotel            0        737               2015
2      Resort Hotel            0          7               2015
3      Resort Hotel            0         13               2015
4      Resort Hotel            0         14               2015
...             ...          ...        ...                ...
29259  Resort Hotel            0        386               2016
29260  Resort Hotel            0         77               2016
29261  Resort Hotel            0        134               2016
29262  Resort Hotel            0        220               2016
29263  Resort Hotel            0        189               2016

      arrival_date_month  arrival_date_week_number  arrival_date_day_of_month  \
0                   July                        27                          1
1                   July                        27                          1
2                   July                        27                          1
3                   July                        27                          1
4                   July                        27                          1
...                  ...                       ...                        ...
29259            October                        43                         20
29260            October                        43                         17
29261            October                        43                         17
29262            October                        43                         17
29263            October                        43                         21

       stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
0                            0                     0       2  ...
1                            0                     0       2  ...
2                            0                     1       1  ...
3                            0                     1       1  ...
4                            0                     2       2  ...
...                        ...                   ...     ...  ...
29259                        1                     3       2  ...
29260                        2                     5       2  ...
29261                        2                     5       2  ...
29262                        2                     5       2  ...
29263                        1                     2       3  ...

       deposit_type  agent company days_in_waiting_list    customer_type  \
0        No Deposit    NaN     NaN                    0        Transient
1        No Deposit    NaN     NaN                    0        Transient
2        No Deposit    NaN     NaN                    0        Transient
3        No Deposit  304.0     NaN                    0        Transient
4        No Deposit  240.0     NaN                    0        Transient
...             ...    ...     ...                  ...              ...
29259    No Deposit    NaN     NaN                    0  Transient-Party
29260    No Deposit    NaN     NaN                    0        Transient
29261    No Deposit  240.0     NaN                    0        Transient
29262    No Deposit  243.0     NaN                    0         Contract
29263    No Deposit  314.0     NaN                    0        Transient

          adr  required_car_parking_spaces  total_of_special_requests  \
0        0.00                            0                          0
1        0.00                            0                          0
2       75.00                            0                          0
3       75.00                            0                          0
4       98.00                            0                          1
...       ...                          ...                        ...
29259   49.00                            0                          0
29260   10.00                            0                          0
29261  100.00                            0                          2
29262   72.75                            0                          0
29263   72.56                            0                          1

       reservation_status reservation_status_date
0               Check-Out              2015-07-01
1               Check-Out              2015-07-01
2               Check-Out              2015-07-02
3               Check-Out              2015-07-02
4               Check-Out              2015-07-03
...                   ...                     ...
29259           Check-Out              2016-10-24
29260           Check-Out              2016-10-24
29261           Check-Out              2016-10-24
29262           Check-Out              2016-10-24
29263           Check-Out                 2016-10

[29264 rows x 32 columns]>

In [7]:
df['arrival_date_day_of_month'].dtype

dtype('int64')

In [8]:
df.dtypes

hotel                              object
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                            int64
babies                              int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                             float64
company                           float64
days_in_waiting_list                int64
customer_type                      object
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                 object
reservation_status_date            object
dtype: object

In [9]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [10]:
df.shape

(29264, 32)

In [11]:
df['arrival_date_day_of_month'].mean()

15.723141060688901

In [12]:
df.groupby('arrival_date_day_of_month')[['lead_time']].mean()

                            lead_time
arrival_date_day_of_month
1                          111.317943
2                          104.389728
3                          110.469450
4                           98.218238
5                           87.209410
6                          112.990077
7                           85.207464
8                          107.348131
9                           90.241080
10                          97.016374
11                          81.450526
12                         136.045814
13                          84.680990
14                         100.302217
15                         120.254764
16                          88.478049
17                         100.276342
18                          79.621963
19                          85.580844
20                         112.714602
21                         112.241989
22                          93.908120
23                          73.171393
24                         101.555227
25                          97.181921
26                         110.074039
27                          78.481363
28                          77.392135
29                          85.001232
30                          93.082941
31                         110.564019

In [13]:
df_sub=df[df['lead_time']>10]
print(df_sub)

              hotel  is_canceled  lead_time  arrival_date_year  \
0      Resort Hotel            0        342               2015
1      Resort Hotel            0        737               2015
3      Resort Hotel            0         13               2015
4      Resort Hotel            0         14               2015
5      Resort Hotel            0         14               2015
...             ...          ...        ...                ...
29259  Resort Hotel            0        386               2016
29260  Resort Hotel            0         77               2016
29261  Resort Hotel            0        134               2016
29262  Resort Hotel            0        220               2016
29263  Resort Hotel            0        189               2016

      arrival_date_month  arrival_date_week_number  arrival_date_day_of_month  \
0                   July                        27                          1
1                   July                        27                          1
3                   July                        27                          1
4                   July                        27                          1
5                   July                        27                          1
...                  ...                       ...                        ...
29259            October                        43                         20
29260            October                        43                         17
29261            October                        43                         17
29262            October                        43                         17
29263            October                        43                         21

       stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
0                            0                     0       2  ...
1                            0                     0       2  ...
3                            0                     1       1  ...
4                            0                     2       2  ...
5                            0                     2       2  ...
...                        ...                   ...     ...  ...
29259                        1                     3       2  ...
29260                        2                     5       2  ...
29261                        2                     5       2  ...
29262                        2                     5       2  ...
29263                        1                     2       3  ...

       deposit_type  agent company days_in_waiting_list    customer_type  \
0        No Deposit    NaN     NaN                    0        Transient
1        No Deposit    NaN     NaN                    0        Transient
3        No Deposit  304.0     NaN                    0        Transient
4        No Deposit  240.0     NaN                    0        Transient
5        No Deposit  240.0     NaN                    0        Transient
...             ...    ...     ...                  ...              ...
29259    No Deposit    NaN     NaN                    0  Transient-Party
29260    No Deposit    NaN     NaN                    0        Transient
29261    No Deposit  240.0     NaN                    0        Transient
29262    No Deposit  243.0     NaN                    0         Contract
29263    No Deposit  314.0     NaN                    0        Transient

          adr  required_car_parking_spaces  total_of_special_requests  \
0        0.00                            0                          0
1        0.00                            0                          0
3       75.00                            0                          0
4       98.00                            0                          1
5       98.00                            0                          1
...       ...                          ...                        ...
29259   49.00                            0                          0
29260   10.00                            0                          0
29261  100.00                            0                          2
29262   72.75                            0                          0
29263   72.56                            0                          1

       reservation_status reservation_status_date
0               Check-Out              2015-07-01
1               Check-Out              2015-07-01
3               Check-Out              2015-07-02
4               Check-Out              2015-07-03
5               Check-Out              2015-07-03
...                   ...                     ...
29259           Check-Out              2016-10-24
29260           Check-Out              2016-10-24
29261           Check-Out              2016-10-24
29262           Check-Out              2016-10-24
29263           Check-Out                 2016-10

[22496 rows x 32 columns]

In [14]:
df[['is_canceled','adults']]

       is_canceled  adults
0                0       2
1                0       2
2                0       1
3                0       1
4                0       2
...            ...     ...
29259            0       2
29260            0       2
29261            0       2
29262            0       2
29263            0       3

[29264 rows x 2 columns]

In [15]:
df[10:20]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
10,Resort Hotel,1,23,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,123.00,0,0,Canceled,2015-06-23
11,Resort Hotel,0,35,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,145.00,0,0,Check-Out,2015-07-05
12,Resort Hotel,0,68,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,97.00,0,3,Check-Out,2015-07-05
13,Resort Hotel,0,18,2015,July,27,1,0,4,2,...,No Deposit,241.0,NaN,0,Transient,154.77,0,1,Check-Out,2015-07-05
14,Resort Hotel,0,37,2015,July,27,1,0,4,2,...,No Deposit,241.0,NaN,0,Transient,94.71,0,0,Check-Out,2015-07-05
15,Resort Hotel,0,68,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,97.00,0,3,Check-Out,2015-07-05
16,Resort Hotel,0,37,2015,July,27,1,0,4,2,...,No Deposit,8.0,NaN,0,Contract,97.50,0,0,Check-Out,2015-07-05
17,Resort Hotel,0,12,2015,July,27,1,0,1,2,...,No Deposit,240.0,NaN,0,Transient,88.20,0,0,Check-Out,2015-07-02
18,Resort Hotel,0,0,2015,July,27,1,0,1,2,...,No Deposit,NaN,110.0,0,Transient,107.42,0,0,Check-Out,2015-07-02
19,Resort Hotel,0,7,2015,July,27,1,0,4,2,...,No Deposit,250.0,NaN,0,Transient,153.00,0,1,Check-Out,2015-07-05

In [16]:
df_sub.shape

(22496, 32)

In [17]:
df.iloc[0]

hotel                             Resort Hotel
is_canceled                                  0
lead_time                                  342
arrival_date_year                         2015
arrival_date_month                        July
arrival_date_week_number                    27
arrival_date_day_of_month                    1
stays_in_weekend_nights                      0
stays_in_week_nights                         0
adults                                       2
children                                     0
babies                                       0
meal                                        BB
country                                    PRT
market_segment                          Direct
distribution_channel                    Direct
is_repeated_guest                            0
previous_cancellations                       0
previous_bookings_not_canceled               0
reserved_room_type                           C
assigned_room_type                           C
booking_changes                              3
deposit_type                        No Deposit
agent                                      NaN
company                                    NaN
days_in_waiting_list                         0
customer_type                        Transient
adr                                        0.0
required_car_parking_spaces                  0
total_of_special_requests                    0
reservation_status                   Check-Out
reservation_status_date             2015-07-01
Name: 0, dtype: object

In [18]:
df.iloc[-1]

hotel                             Resort Hotel
is_canceled                                  0
lead_time                                  189
arrival_date_year                         2016
arrival_date_month                     October
arrival_date_week_number                    43
arrival_date_day_of_month                   21
stays_in_weekend_nights                      1
stays_in_week_nights                         2
adults                                       3
children                                     0
babies                                       0
meal                                        BB
country                                    IRL
market_segment                       Online TA
distribution_channel                     TA/TO
is_repeated_guest                            0
previous_cancellations                       0
previous_bookings_not_canceled               0
reserved_room_type                           D
assigned_room_type                           D
booking_changes                              0
deposit_type                        No Deposit
agent                                    314.0
company                                    NaN
days_in_waiting_list                         0
customer_type                        Transient
adr                                      72.56
required_car_parking_spaces                  0
total_of_special_requests                    1
reservation_status                   Check-Out
reservation_status_date                2016-10
Name: 29263, dtype: object

In [19]:
df.iloc[:,0]

0        Resort Hotel
1        Resort Hotel
2        Resort Hotel
3        Resort Hotel
4        Resort Hotel
             ...
29259    Resort Hotel
29260    Resort Hotel
29261    Resort Hotel
29262    Resort Hotel
29263    Resort Hotel
Name: hotel, Length: 29264, dtype: object

In [20]:
df.iloc[0:7]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.0,0,0,Check-Out,2015-07-03

In [21]:
df_sorted=df.sort_values(by='arrival_date_year')
df_sorted.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
14742,Resort Hotel,1,259,2015,September,38,17,0,3,1,...,Non Refund,NaN,223.0,0,Transient,33.3,0,0,Canceled,2015-01-21
14741,Resort Hotel,1,259,2015,September,38,17,0,3,1,...,Non Refund,NaN,223.0,0,Transient,33.3,0,0,Canceled,2015-01-21
14740,Resort Hotel,1,259,2015,September,38,17,0,3,1,...,Non Refund,NaN,223.0,0,Transient,33.3,0,0,Canceled,2015-01-21
14739,Resort Hotel,1,259,2015,September,38,17,0,3,1,...,Non Refund,NaN,223.0,0,Transient,33.3,0,0,Canceled,2015-01-21

In [22]:
df_sorted.sort_values(by=['arrival_date_year','lead_time'],ascending=[True,False])
df_sorted.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
14742,Resort Hotel,1,259,2015,September,38,17,0,3,1,...,Non Refund,NaN,223.0,0,Transient,33.3,0,0,Canceled,2015-01-21
14741,Resort Hotel,1,259,2015,September,38,17,0,3,1,...,Non Refund,NaN,223.0,0,Transient,33.3,0,0,Canceled,2015-01-21
14740,Resort Hotel,1,259,2015,September,38,17,0,3,1,...,Non Refund,NaN,223.0,0,Transient,33.3,0,0,Canceled,2015-01-21
14739,Resort Hotel,1,259,2015,September,38,17,0,3,1,...,Non Refund,NaN,223.0,0,Transient,33.3,0,0,Canceled,2015-01-21